config/routes.rb
AAAWebsite::Application.routes.draw do
 devise_for :admin_users, ActiveAdmin::Devise.config
 ActiveAdmin.routes(self)

  resources :comments

  devise_for :users

  resources :events

  root :to => 'aaa_core#index'

  match '/events', :to => 'aaa_core#events'

  match '/shop', :to => 'aaa_core#shop'

  match '/discussion', :to => 'aaa_core#discussion'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :details, :event_id

  validates_presence_of :event_id, :details, :author

  belongs_to :event 

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :title, :image

  mount_uploader :image, ImageUploader

  validates_presence_of :title, :date, :description, :image

  has_many :comments, :dependent => :destroy
end

app/models/sales_item.rb
class SalesItem < ActiveRecord::Base
  attr_accessible :description, :name, :price, :image
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/aaa_core_controller.rb
class AaaCoreController < ApplicationController
  def index
  	@title = "Home"
  end

  def shop
  	@title = "Shop"
    @sales_items = SalesItem.all
  end

  def discussion
  	@title = "Discussion Forum"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new(event_id: params[:event_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
before_filter :authenticate_user!, :except => [:index,:show]
respond_to :html, :xml, :json
  # GET /events
  # GET /events.json
  
  def index
    @events = Event.all
    respond_with(@events)
    
      #format.json { render json: @events }
    #end

  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
  def require_authentication

  end


end

app/helpers/aaa_core_helper.rb
module AaaCoreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
# Return a title on per-page basis.

	def title 
		base_title = "Ashtead Allotments Association"
		if @title.nil?
			base_title

		else
  		"#{base_title} | #{@title}"
		end
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/aaa_core/discussion.html.erb
<h1>AaaCore#discussion</h1>
<p>Find me in app/views/aaa_core/discussion.html.erb</p>

app/views/aaa_core/events.html.erb
<h1>AaaCore#events</h1>
<p>Find me in app/views/aaa_core/events.html.erb</p>

app/views/aaa_core/index.html.erb
<article>
  
  <section id='main'>
  <h1>This section is abot MEH</h1>
   <p>
      New paragrah here sajndkjsnf
   </p>

  <p>
    Blah blah blah MEH 
  </p>
  
  </section>


  <section id="sidebar">
    <h1>This section is about BLAH</h1>
    <p>
    Blah blah blah MEH  dsfjkbdsjfsdbhfbdslj
   </p>
  
  </section>

</article>

app/views/aaa_core/shop.html.erb
<article id ="shop">

  <% @sales_items.each do |sales_item| %>
    <section>
      <h1><%= sales_item.name %></h1>
      <p> <%= image_tag sales_item.image_url(:thumb) if sales_item.image? %>
      <p>
         <%= sales_item.description %>
      </p>
      <p>
        <%= sales_item.price %>
      </p>
    </section>
    <% end %>

</article>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :event_id %>

  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Details</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.event_id %></td>
    <td><%= comment.details %></td>
    <td><%= comment.author %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @comment.event_id %>
</p>

<p>
  <b>Details:</b>
  <%= @comment.details %>
</p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/events/_form.html.erb
<%= form_for @event, :html => {:multipart => true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<article id="events">

  <% @events.each do |event| %>
   <section>
    <h1><%= event.title %></h1>
    <h2>Date of event: <%= event.date %></h2>
    <p>
      <%= event.description %>
    </p>

    <p>
      <%= image_tag event.image_url(:thumb) if event.image? %>
    <% if user_signed_in? %>
     <p>
      <%= link_to 'Show',event %>
      <%= link_to 'Edit',edit_event_path(event) %>
      <%= link_to 'Destroy', event, confirm: 'Are you sure?',method: :delete %>
      <p>
    <% end %>
  </section>
  <% end %>

  <% if user_signed_in? %>
   <section>
     <%= link_to 'New Event', new_event_path %>
   </section>
  <% end %>

</article>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'New Comment', new_comment_path(event_id:@event) %>
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer>

 &copy;<% Time.now.year %> Ashtead Allotments Association

</footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">
  <nav id="utility">
    <% if user_signed_in? %>
    Signed in as <%= current_user.email %>:
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
   <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
   <% end %>
 </nav>
	<h1> Ashtead Allotments Association</h1>
	<h2> Healthy Eating and Exercise preserves Life's Balance</h2>
</header>

app/views/layouts/_navigation.html.erb
<nav id="main_nav" role="navigation">
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Events", events_path %></li>
		<li><%= link_to "Discussion", discussion_path %></li>
		<li><%= link_to "Shop", shop_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset = "utf-8">
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<%= render 'layouts/header' %>

<p class="notice"><%= notice %></p>
<p class="alert" ><%= alert %></p>


<%= render 'layouts/navigation' %>

<%= yield %>

<%= render 'layouts/footer' %>
</div>


</body>
</html>